namespace Microsoft.Azure.Pipelines.CoveragePublisher.Publishers.AzurePipelines
{
    internal static class Constants
    {
        public const string ReportDirectory = "Code Coverage Report";
        public const string DefaultIndexFile = "index.html";
        public const string HtmIndexFile = "index.htm";
        public const string NewIndexFile = "indexnew.html";

        // Non framed html summary generated by cobertura
        public const string DefaultNonFrameFileCobertura = "frame-summary.html";

        internal static class EnvironmentVariables
        {
            public const string BuildId = "Build.BuildId";
            public const string BuildContainerId = "Build.ContainerId";
            public const string AccessToken = "System.AccessToken";
            public const string ProjectId = "System.TeamProjectId";
            public const string CollectionUri = "System.TeamFoundationCollectionUri";
        }

        internal static class ArtifactUploadEventProperties
        {
            public const string ContainerFolder = "containerfolder";
            public const string ArtifactName = "artifactname";
            public const string ArtifactType = "artifacttype";
            public const string Browsable = "Browsable";
        }
    }
}
